generate_video_script_samples=""" Aqui tienes ejemplos de scripts de videos virales de otras temáticas
1: Los herafines son los seres más poderosos del ejército de los cielos. La Biblia los describe como seres enormes con seis alas y muchos ojos, además de estar rodeados de fuego. Los que rubines son los segundos en poder, sólo estando por debajo de los herafines. La Biblia los describe como un ser con cuerpo de hombre, pero con cuatro caras, león, haguila, torro y una humana en la mitad. Estos ángeles tienen cuatro alas y cumplen la función de guardianes. Se dice que Satanás fue un querubín. Los ángeles de los tronos, que ocupan el tercer lugar en la jerarquía angélica, sólo estando por detrás de los herafines y los querubines. Se reúnen directamente con Dios para discutir sus buenos propósitos para todos y para todo en el universo, y como los ángeles pueden ayudar a cumplir esos propósitos.
2: Era había quedado horrorizada después de ver a su hijo por primera vez, pues este era muy diferente a cualquier otro recién ha sido, era demasiado feo, tenía bello en todo el cuerpo, sus rasgos eran demasiado rústicos y su piel era tan oscura como el ollín. El niño, al sentir el crudo rechazo de su madre, rompió en llanto, y allí fue cuando era lo vio aún más feo. Desesperada la Dios agritaba en el olimpo que ese no era su hijo, luego lo tomó en sus brazos y por el horror lanzó al bebé desde el olimpo hacia el mar. El pequeño efecto cayó violentamente en el mar, pero a pesar de ello, sobrevivió, y empezó a moverse buscando quien los salve, así desde las profundidades la océanidad tétis escucha el estreno, y sube hasta la superficie para ver qué era lo que había sucedido. En cuanto llegó vio al pequeño recién ha sido golpeado por las aguas, envuelto en un llanto incontrolable, tétis sabía que el bebé era de la Diosa era.
3: ¿Por qué los tragoan europeos son tan raros? Cuando miramos a lo que llamamos tragoanes en las diferentes culturas del mundo, es muy fácil ver que el Dragon europeo es un poco bastante diferente al resto. Y esto puede que sea porque no es un dragon. Wálvenos no de la misma forma que los otros. La palabra dragon viene del Diego Dracol. Y un dragon grego es una serpiente con cresta y a veces barba. Lo que encaja bastante bien con los otros tragoanes. Pero el dragon no lo puede ver no puede que venga de otra criatura mitológica. No muy dragon sino el grifo. Los grisos de la tradición grieca eran codiciosos protectores de oro y vivían en las rutas de las montañas. Además, te cree que el grifo vendría de la cultura mesopotamica. En concreto dio un ser que se usaba para representar al dios de las tormentas, el Osion Ball. Un ser con cuerpo de león, a las de Ángela y que escupía fuego.
4: Minos rezó a Poseidón para que le mandara un toro blanco como la nieve, un signo de apoyo, el toro de creta. Él tenía que matar al toro para mostrar honor a la edad, pero decidió quedárselo por su belleza. Pensó que a Poseidón no le importaría si mantenía el toro y sacrificaba un oprópio. Para castigar a Minos, Poseidón hizo que Pacifa, la esposa de Minos, se enamorara profundamente del toro. Pacifa hizo que el artesano de Dalole hiciera una vaca hueca de madera metiéndose dentro para aparearse con el toro blanco. Su descendencia fue el monstruoso minotauro. Pacifa lo cuidó, pero creció y se volvió feroz, al ser el hijo no natural de una mujer y una bestia, no tuvo una fuente natural de alimentarse por lo que sólo comía carne humana, y conforme crecía se volvía más alvaje.
5: En el reino de los cielos desde el comienzo de todos los tiempos, Dios creó a un gran ejército celestial conformado por varios seres espirituales muy poderosos, que ayudarían a proteger la creación divina, la gracia de Dios y el paraíso. Seres tan poderosos que tendrían la potestad divina de combater y derrotar a los entes malignos que abundan en la tierra y en el abismo. Los ángeles son los principales siervos de Dios y los defensores del paraíso. Se cree que en los cielos existe una jerarquía celestial muy marcada que la conforma a los ángeles y su posicionamiento en ella se ve dispuesta por su rango, importancia y poder sobre los demás. La jerarquía celestial está conformada por tres esferas o jerarquías ángelicas que poseen diferentes coros ángelicales que ayudan a controlar el orden cósmico y a dirigir a las masas espirituales.
6: Los herafines son los ángeles que están ubicados en lo que se ha llamado los 9 coros celestiales existentes, pertenecen al nivel jerarquico más alto, siendo los más poderosos del ejército de los sieros. El término seraphines de origen hebreo, y significa ardiente. Isayas describe a los herafines como seres que poseen 6 salas, 2 para cubrir su cara, 2 para cubrir sus pies y 2 para volar, también se dice que tienen muchos ojos. En la creencia cristiana es el mayor rango angelical, y en la tradición judía ocupa el quinto puesto de las 10 jerarquías de ángeles que existen.
7: Elena, considerada la hija más hermosa deseos, propiciaría uno de los eventos más catastróficos de la mitología griega a causa de un amor prohibido. Portadora de unos labios ojos como rubies, inspiraba los más oscuros deseos de todo aquel que llegaba a conocerla. Mujer de cabello escarlata, piel armoniosa e impoluta, Elena era más que una simple mujer bella, los detalles en cada facción de su cuerpo en altecían sus virtudes. No había habitante ingresia que no quedara flechado a su paso, deseosos de merecer el placer superfluo que conllevaría disfrutar una caricia de esta casi diosa de la belleza. Sin embargo, ella podía enamorar a cualquiera, más encontraba cierta dificultada a la hora de dar dienda suelta a sus propios sentimientos. En todo el territorio griego solamente menelao, Rey de Esparta, fue merecedor de su compañía al proveerla de los lujos y comodidades dignos de su perfección.
8: Moisés había pasado su vida entera en busca de la tierra prometida, viajó por más de 40 años por el desierto desde Egipto, en donde le fue revelado por Dios que su destino estaba en Canal y así también el de su pueblo. Cuando llegó a la tierra con la que tanto soñaba y la que por muchos años buscó, su pueblo fue bienvenido, las puertas de Canal se abrieron y su pueblo se lebró que al fin la tierra prometida por Dios les fue entregada. Moisés estaba muy feliz por lo que había logrado, pues toda su vida adoró a Dios y hizo todo aquello que le pedía cuando le hablaba, sin embargo, cuando Moisés quiso entrar a Canal no lo logró, pues su entrada a la tierra prometida se le fue prohibida. Moisés lloró amargamente y a pesar de no entrar, él deseó con su espíritu ver la tierra que por tantos años buscó. Entonces apareció Dios y le dijo, Moisés, has logrado entregarle a tu pueblo mi bendición, cuando tú no has de entrar a Canal, pues no has cumplido con todo lo que yo te he ordenado.
"""

generate_images_description_and_split_text=""" Here are examples of text and image pairs:
'text': 'Imagínate a Un héroe olvidado en la Iliada de Homero: Patroclo, el amigo íntimo de Aquiles.', 'image': "An old Greek hero sad."
'text': 'Enamorado de Aquiles, le suplica ir a batalla con su armadura para infundir miedo en los troyanos.', 'image': 'An old Greek hero with and golden armor.'
"""